// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgidcdkndjklcluqtroe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnaWRjZGtuZGprbGNsdXF0cm9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMzg0MzYsImV4cCI6MjA2NjgxNDQzNn0.BTUt0VMqQusqMoJWjkUmMUnleyUJbwTvj_4gsMZoUQc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});